#!/bin/sh
git pull && git submodule update --init --recursive --merge && git submodule foreach git fetch origin && git submodule foreach git merge origin/master && git submodule update --init --recursive --merge
